import { type } from "os";

export const texts = {
  pt: {
    title: "Mail2TTS: Central de Tickets Inteligente",
    desc: "Transforme a experiência dos seus usuários com uma interface simples e moderna para abertura de tickets. Integre facilmente com Zammad ou outros sistemas de ticketing. Ideal para empresas que buscam agilidade, padronização e integração.",
    items: [
      "Interface centralizada e intuitiva",
      "Integração nativa com Zammad",
      "Possibilidade de integração com outros sistemas",
      "Customização para sua empresa",
      "Segurança e privacidade",
    ],
    button: "Teste grátis agora",
    subject: "Assunto",
    subject_description: "Preencha o Assunto",
    category: "Categoria",
    category_description: "Selecione Categoria",
    type: "Tipo",
    type_description: "Selecione Tipo",
    item: "Item",
    item_description: "Selecione Item",
    impact: "Impacto",
    impact_description: "Selecione Impacto",
    urgency: "Urgência",
    urgency_description: "Selecione Urgência",
    description: "Descrição",
    check: "Ver resumo",
    email: "Criar Email",
    select: "Selecione",
    summary: "Resumo",
  },
  en: {
    title: "Mail2TTS: Smart Ticket Center",
    desc: "Transform your users' experience with a simple and modern interface for ticket creation. Easily integrate with Zammad or other ticketing systems. Perfect for companies seeking agility, standardization, and integration.",
    items: [
      "Centralized and intuitive interface",
      "Native integration with Zammad",
      "Possible integration with other systems",
      "Customization for your company",
      "Security and privacy",
    ],
    button: "Try it free now",
    subject: "Subject",
    subject_description: "Fill in the Subject",
    category: "Category",
    category_description: "Select Category",
    type: "Type",
    type_description: "Select Type",
    item: "Item",
    item_description: "Select Item",
    impact: "Impact",
    impact_description: "Select Impact",
    urgency: "Urgency",
    urgency_description: "Select Urgency",
    description: "Description",
    check: "Check",
    email: "Create Email",
    select: "Select",
    summary: "Summary",
  },
  it: {
    title: "Mail2TTS: Centro Ticket Intelligente",
    desc: "Trasforma l'esperienza dei tuoi utenti con un'interfaccia semplice e moderna per l'apertura dei ticket. Integra facilmente con Zammad o altri sistemi di ticketing. Ideale per aziende che cercano agilità, standardizzazione e integrazione.",
    items: [
      "Interfaccia centralizzata e intuitiva",
      "Integrazione nativa con Zammad",
      "Possibilità di integrazione con altri sistemi",
      "Personalizzazione per la tua azienda",
      "Sicurezza e privacy",
    ],
    button: "Prova gratis ora",
    subject: "Oggetto",
    subject_description: "Compila l'Oggetto",
    category: "Categoria",
    category_description: "Seleziona Categoria",
    type: "Tipo",
    type_description: "Seleziona Tipo",
    item: "Elemento",
    item_description: "Seleziona Elemento",
    impact: "Impatto",
    impact_description: "Seleziona Impatto",
    urgency: "Urgenza",
    urgency_description: "Seleziona Urgenza",
    description: "Descrizione",
    check: "Vedi riepilogo",
    email: "Crea Email",
    select: "Seleziona",
    summary: "Riepilogo",
  },
};
